mutation loginWithActionGrant($input: LoginWithActionGrantInput!) {
   loginWithActionGrant(login: $input) {
      account {
         profiles {
            id
            name
         }
      }
   }
}
