package main

import (
   "net/http"
   "net/url"
   "os"
)

func main() {
   var req http.Request
   req.Header = http.Header{}
   req.URL = &url.URL{}
   req.URL.Host = "cfd-v4-service-stitcher-dash-use1-1.prd.pluto.tv"
   req.URL.Path = "/v2/stitch/dash/episode/6495eff09263a40013cf63a5/main.mpd"
   value := url.Values{}
   value["jwt"] = []string{jwt}
   req.URL.RawQuery = value.Encode()
   req.URL.Scheme = "https"
   resp, err := http.DefaultClient.Do(&req)
   if err != nil {
      panic(err)
   }
   err = resp.Write(os.Stdout)
   if err != nil {
      panic(err)
   }
}

const jwt = "eyJhbGciOiJIUzI1NiIsImtpZCI6ImMxODRlNzg3LWE4MTYtNDI5ZC1iYzZkLTY4NjUzODcxNmU1ZSIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSUQiOiI2NGFkN2ZkOS1kNGFmLTExZjAtOTMwNi1hZWE0NzI5ZWE0ODYiLCJjbGllbnRJUCI6IjcyLjE4MS4yMy4zOCIsImNpdHkiOiJJcnZpbmciLCJwb3N0YWxDb2RlIjoiNzUwNjMiLCJjb3VudHJ5IjoiVVMiLCJkbWEiOjYyMywiYWN0aXZlUmVnaW9uIjoiVVMiLCJkZXZpY2VMYXQiOjMyLjkxOTk5ODE2ODk0NTMxLCJkZXZpY2VMb24iOi05Ni45NzAwMDEyMjA3MDMxMiwicHJlZmVycmVkTGFuZ3VhZ2UiOiJlbiIsImRldmljZVR5cGUiOiJ3ZWIiLCJkZXZpY2VWZXJzaW9uIjoiMTI4LjAuMCIsImRldmljZU1ha2UiOiJmaXJlZm94IiwiZGV2aWNlTW9kZWwiOiJ3ZWIiLCJhcHBOYW1lIjoid2ViIiwiYXBwVmVyc2lvbiI6IjkuMTguMC0zMjI5NmQ0N2M5ODgyNzU0ZTM2MGYxYjI4YTMzMDI3YzU0Y2JhZDE2IiwiY2xpZW50SUQiOiJlYjcyMjU5MS03MzNlLTQ1OWUtOGQ1OC05N2M3YmJiZGYxOGMiLCJjbUF1ZGllbmNlSUQiOiIiLCJpc0NsaWVudEROVCI6ZmFsc2UsInVzZXJJRCI6IiIsImxvZ0xldmVsIjoiREVGQVVMVCIsInRpbWVab25lIjoiQW1lcmljYS9DaGljYWdvIiwic2VydmVyU2lkZUFkcyI6ZmFsc2UsImUyZUJlYWNvbnMiOmZhbHNlLCJmZWF0dXJlcyI6eyJhZExvYWQiOnsiY29ob3J0IjoiIn0sIm11bHRpQXVkaW8iOnsiZW5hYmxlZCI6dHJ1ZX0sIm11bHRpUG9kQWRzIjp7ImVuYWJsZWQiOnRydWV9LCJzZWFyY2hBUEkiOnsicXVlcnlWZXJzaW9uIjoiaHlicmlkIn0sInN0aXRjaGVySGxzTmciOnsiZGVtdXhlZEF1ZGlvIjoiaml0In0sInN0aXRjaGVySGxzTmdWbGwiOnsiZW5hYmxlZCI6dHJ1ZX0sInN0aXRjaGVySGxzTmdWb2QiOnsiZW5hYmxlZCI6dHJ1ZX19LCJmbXNQYXJhbXMiOnsiZndWY0lEMiI6ImViNzIyNTkxLTczM2UtNDU5ZS04ZDU4LTk3YzdiYmJkZjE4YyIsImZ3VmNJRDJDb3BwYSI6ImViNzIyNTkxLTczM2UtNDU5ZS04ZDU4LTk3YzdiYmJkZjE4YyIsImN1c3RvbVBhcmFtcyI6eyJmbXNfbGl2ZXJhbXBfaWRsIjoiIiwiZm1zX2VtYWlsaGFzaCI6IiIsImZtc19zdWJzY3JpYmVyaWQiOiIiLCJmbXNfaWZhIjoiIiwiZm1zX2lkZnYiOiIiLCJmbXNfdXNlcmlkIjoiZWI3MjI1OTEtNzMzZS00NTllLThkNTgtOTdjN2JiYmRmMThjIiwiZm1zX3ZjaWQydHlwZSI6InVzZXJpZCIsImZtc19yYW1wX2lkIjoiIiwiZm1zX2hoX3JhbXBfaWQiOiIiLCJmbXNfYmlkaWR0eXBlIjoiIiwiX2Z3XzNQX1VJRCI6IiIsImZtc19ydWxlaWQiOiIxMDAwMCwxMDAwOSJ9fSwiZHJtIjp7Im5hbWUiOiJ3aWRldmluZSIsImxldmVsIjoiTDMifSwiaXNzIjoiYm9vdC5wbHV0by50diIsInN1YiI6InByaTp2MTpwbHV0bzpkZXZpY2VzOlVTOlpXSTNNakkxT1RFdE56TXpaUzAwTlRsbExUaGtOVGd0T1Rkak4ySmlZbVJtTVRoaiIsImF1ZCI6IioucGx1dG8udHYiLCJleHAiOjE3NjUzMzc0MjIsImlhdCI6MTc2NTI1MTAyMiwianRpIjoiOWUwMWM4MjQtOTA2OC00ZWYzLWFlNGMtOTU5YjAwMTc4MDk4In0.K4H3egwu6C_dpGarvOwl7DFT7o8cyDH9qWe-Gt7_JvI"


